name: Compile WASM and Push to Website

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "latest"

      - name: Compile C++ to WASM
        run: |
          mkdir -p public
          em++ lkmc-wasm.cpp -o public/lkmc-wasm.js -O3 -std=c++17 -fexceptions -sINITIAL_MEMORY=268435456 -sALLOW_MEMORY_GROWTH=1 -sEXPORT_ES6=1 -sMODULARIZE=1 -sEXPORTED_FUNCTIONS="['_set_params','_set_carbon_species_energy','_get_carbon_species_grid','_update_simulation_params','_init_simulation','_mark_carbon','_unmark_carbon','_finalize_carbon_placement','_run_steps','_get_lattice_data','_get_width','_get_stats_json','_get_stats_json_len','_get_height','_get_lattice','_get_lattice_size','_get_fill','_get_passivated','_get_step','_get_time','_get_wall_time','_play','_pause','_stop','_step_once','_playback_tick','_set_batch_size','_set_stats_interval','_get_stats_interval','_get_playback_state','_get_terminated','_get_cell_coordination','_get_snapshot_count','_get_snapshot_step','_get_snapshot_lattice','_save_state','_get_save_state_len','_load_state','_peek_state_dimensions','_run_batch','_get_batch_json','_cleanup_simulation','_force_update_frontend','_malloc','_free']" -sEXPORTED_RUNTIME_METHODS="['ccall','cwrap','HEAP8','HEAPU8','HEAP32','HEAPF64','wasmMemory']"
      - name: Push Build Artifacts to Destination Repo
        if: github.ref == 'refs/heads/main'
        env:
          DEST_PAT: ${{ secrets.UPDATE_WASM_PAT }}
        run: |
          # Clone the repo into a temp folder
          git clone https://x-access-token:${DEST_PAT}@github.com/Rice-Material-Science-Lab/lithium-website.git dest-repo

          # Copy js and wasm files into the public folder
          mkdir -p dest-repo/public/
          cp public/lkmc-wasm.js dest-repo/public/
          cp public/lkmc-wasm.wasm dest-repo/public/

          # Commit and push changes
          cd dest-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add public/lkmc-wasm.js public/lkmc-wasm.wasm

          # Only commit if changes actually exist to avoid failing the workflow step
          git diff-index --quiet HEAD || git commit -m "Automated WASM build update"
          git push origin main