name: Compile WASM and Push to Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "latest"

      - name: Compile C++ to WASM
        run: |
          mkdir -p public
          emcc lkmc-wasm.cpp -o public/lkmc-wasm.js -O3 -fexceptions -sEXPORT_ES6 -sMODULARIZE -sEXPORTED_FUNCTIONS="['_init_simulation','_run_steps','_get_lattice','_get_width','_get_height','_get_step','_get_time', '_get_snapshot_json', '_cleanup_simulation']" -sEXPORTED_RUNTIME_METHODS="['ccall','cwrap','UTF8ToString']"

      - name: Push Build Artifacts to Destination Repo
        env:
          DEST_PAT: ${{ secrets.UPDATE_WASM_PAT }}
        run: |
          # Clone the repo into a temp folder
          git clone https://x-access-token:${DEST_PAT}@github.com/Rice-Material-Science-Lab/lithium-website.git dest-repo

          # Copy js and wasm files into the public folder
          mkdir -p dest-repo/public/
          cp public/lkmc-wasm.js dest-repo/public/
          cp public/lkmc-wasm.wasm dest-repo/public/

          # Commit and push changes
          cd dest-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add public/lkmc-wasm.js public/lkmc-wasm.wasm

          # Only commit if changes actually exist to avoid failing the workflow step
          git diff-index --quiet HEAD || git commit -m "Automated WASM build update"
          git push origin main
